defmodule Day7Test do
  use ExUnit.Case

  def example_input do
    """
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............
    """
    |> String.trim_trailing("\n")
  end

  test "part1" do
    assert Day7.part1(example_input()) == 21
  end

  test "part2" do
    assert Day7.part2(example_input()) == 40
  end
end
